name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, mysql, curl
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader
      
      - name: Create Static Site Directory
        run: |
          mkdir -p _site
          cp -r index.html css js images _site/
          cp -r vendor _site/
          # Create static version of PHP endpoints
          mkdir -p _site/api
          echo '{"status":"success","message":"API endpoint simulation"}' > _site/api/auth.json
          echo '{"status":"success","message":"Message received"}' > _site/api/contact.json
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
