name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev cmake build-essential
          npm install

      - name: Build C++ game
        run: |
          cd cpp
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config ${{env.BUILD_TYPE}}
          cd ../..
          mkdir -p dist/cpp
          cp cpp/build/game dist/cpp/ || true
          cp -r cpp/assets dist/cpp/ || true

      - name: Build web assets
        run: |
          mkdir -p dist
          cp -r index.html css js images dist/ || true
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          preview: false
