name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SFML Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev cmake build-essential

      - name: Build C++ Game
        run: |
          cd cpp
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Upload C++ Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-game
          path: cpp/build/process_game

  build-web:
    runs-on: ubuntu-latest
    needs: build-cpp
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Web Assets
        run: |
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download C++ Game
        uses: actions/download-artifact@v3
        with:
          name: cpp-game
          path: dist/cpp

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
